package com.yonatan.sonora.models;

import java.io.Serializable;

/**
 * מחלקה המייצגת המלצה שנוצרה על ידי מנוע הבינה המלאכותית Sonora AI.
 * כוללת את הפריט המומלץ, אחוז ההתאמה (Match Score) ונימוק אלגוריתמי מילולי.
 *
 * Recommendation entity generated by Sonora AI Engine.
 */
public class Recommendation implements Serializable {

    private static final long serialVersionUID = 1L;

    private MusicItem musicItem;
    private int matchPercentage; // e.g., 95
    private String aiReasoning;
    private String matchedAttribute;

    public Recommendation() {
        this.musicItem = null;
        this.matchPercentage = 80;
        this.aiReasoning = "";
        this.matchedAttribute = "";
    }

    public Recommendation(MusicItem musicItem, int matchPercentage, String aiReasoning, String matchedAttribute) {
        this.musicItem = musicItem;
        this.matchPercentage = matchPercentage;
        this.aiReasoning = aiReasoning;
        this.matchedAttribute = matchedAttribute;
    }

    public MusicItem getMusicItem() {
        return musicItem;
    }

    public void setMusicItem(MusicItem musicItem) {
        this.musicItem = musicItem;
    }

    public int getMatchPercentage() {
        return matchPercentage;
    }

    public void setMatchPercentage(int matchPercentage) {
        this.matchPercentage = matchPercentage;
    }

    public String getAiReasoning() {
        return aiReasoning;
    }

    public void setAiReasoning(String aiReasoning) {
        this.aiReasoning = aiReasoning;
    }

    public String getMatchedAttribute() {
        return matchedAttribute;
    }

    public void setMatchedAttribute(String matchedAttribute) {
        this.matchedAttribute = matchedAttribute;
    }
}
